package nl.gwe.datalists;

public enum Meters {
	LOW_ELECTRICITY_PURCHASED,
	LOW_ELECTRICITY_DELIVERED,
	HIGH_ELECTRICITY_PURCHASED,
	HIGH_ELECTRICITY_DELIVERED,
	TOTAL_ELECTRICITY,
	GAS_PURCHASED,
	WATER_PURCHASED
}
